### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Tan35** [brianlovin/brian-lovin-next#1501]
![image](https://user-images.githubusercontent.com/45460542/122937102-46272580-d3a4-11eb-947c-93bfc8281760.png)
I'm sorry to interrupt! But I've tried many times

**Comment by brianlovin** [comment]
I believe this is because this repo doesn't have all of the secrets required to run the app. If you project search for `.replace` you should fine where this method is being called, and you could remove that code. Alternatively, if you set up your own env variables (in this case, setting up all the Firebase variables, I think), then this will work 😊
